server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: false
    show-sql: false
    open-in-view: false
  profiles:
    active: default,prod
  mvc:
    pathmatch:
      matching-strategy: path-pattern-parser

springdoc:
  packages-to-scan: com.happy3friends.toiletmapbackend.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: false
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    default-models-expand-depth: -1
